version: '3'
services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/haproxy/certs:ro
    ports:
      - "5554:80"
      - "5555:443"
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
